### ISSUE TITLE
Cannot use my own audio files.

### ISSUE THREAD

**Issue by manskx** [Nachimak28/LAI-voice-search-openai-whisper-demo#7]
I launched the app on the cloud, I could run the provided examples, but could not use my own samples.

**Comment by Nachimak28** [comment]
What's the file format of your audio sample? I believe whisper can process multiple file formats like mp3, wav etc but gradio's audio file upload component only accepts .wav files. If there's some problem with a wav file too, I can test it out on my end if you can send me the file and see what's going wrong.

**Comment by manskx** [comment]
Hi @Nachimak28 I tried both of these .wav files and didn't work.
[Archive.zip](https://github.com/Nachimak28/LAI-voice-search-openai-whisper-demo/files/9727722/Archive.zip)

**Comment by Nachimak28** [comment]
So sorry about this. Don't mean to waste your time. I'll do an exhaustive testing with these and more wav files available on the web and local+cloud testing. Shall resubmit for the gallery only when I know for sure it won't fail.

**Comment by Nachimak28** [comment]
Hi @manskx just to understand the issue about these files, may I ask what error did you get while running inference for these wav files? 
I checked them out locally as well as in lit cloud once and I got the expected outputs, since its running on a cpu machine it takes a while to generate the text (approx 100 seconds for a 5 second video). 
If the problem you're facing is that you feel like the app is stuck after you upload the wavs, it could be because of the time taken and no progress being shown for the inference. 
I've made some changes you can try out the app now with the mic input instead of file upload [here](https://01gfax73s2tn315zme310fkh4z.litng-ai-03.litng.ai/view/home)

If you wish that I should keep the both the kinds of inputs (file upload as well as mic) please do let me know and I'll do those changes. I've only removed the file upload provision because it didn't feel like a correct way to mimic the search feature available in browsers.

**Comment by manskx** [comment]
Hi @Nachimak28. Thanks for the updates. I tried the app and the mic works, but I notice that it's very slow. I don't think it will be possible to take a couple of minutes just to process a few seconds of sound. How do you think we can improve it and provide value to the app users? cc: @aniketmaurya

**Comment by Nachimak28** [comment]
@manskx Yes, I have been meaning to test it out with a couple of different Compute variations (cpu-large, gpu spot instances or with gpu with idle timeout) for the lightning cloud but have been running short on free time since a couple of weeks 😅
Also I am planning to make more apps later which might require some GPU compute to demonstrate training procedure so was just saving up the credits for that.
I will try running it with the gpu spot instances and see how the credits are being used.

**Comment by Nachimak28** [comment]
@manskx, I've updated the compute type to "gpu" and its doing the inference really quickly. The app is available at [this URL](https://01gfax73s2tn315zme310fkh4z.litng-ai-03.litng.ai/view/home) for testing.

**Comment by Nachimak28** [comment]
Closing this issue for now. If there are any issues, please feel free to reopen this issue.
